POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "JoelGrayson",
    "email": "thejoelgrayson@gmail.com",
    "password": "password"
}


###
POST http://localhost:3001/api/auth/register
Content-Type: application/json


{
    "username": "JoelGrayson2",
    "email": "joel@joelgrayson.com",
    "password": "password2"
}


###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "JoelGrayson2",
    "password": "password2"
}
